version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    container_name: ELASTICSEARCH
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    volumes:
     - ${HOMEDIR}/data/elasticsearch:/usr/share/elasticsearch/data

  fluentd:
    build: ${HOMEDIR}/docker/fluentd
    image: f5networks/fluentd:latest
    container_name: FLUENTD
    ports:
      - 20000:20000/tcp
      - ${FLUENTD_PORT}:20001/${FLUENTD_PROTOCAL}
    volumes:
      - ${HOMEDIR}/conf.d/fluentd.conf:/etc/td-agent/td-agent.conf
      - ${HOMEDIR}/conf.d/fluentd:/etc/td-agent/fluentd
      - ${HOMEDIR}/data/fluentd:/var/log/td-agent/buffer
    environment:
      - FLUENTD_PROTOCAL
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
      - kibana
      - kafka

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.1
    container_name: KIBANA
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - ${HOMEDIR}/conf.d/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ${HOMEDIR}/data/kibana:/usr/share/kibana/data

  ctrlbox:
    build: ${HOMEDIR}/docker/ctrlbox
    image: f5networks/ctrlbox:latest
    container_name: CTRLBOX
    ports:
      - 8000:80
      - 7890:7890
    links:
      - elasticsearch
    depends_on:
      - nginx
      - kibana
      - elasticsearch
      - fluentd
      - kafka
      - logstash
    volumes:
      - ${HOMEDIR}:/root/workdir

  zookeeper:
    image: bitnami/zookeeper:3
    container_name: ZOOKEEPER
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    
  kafka:
    image: bitnami/kafka:2
    container_name: KAFKA
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - ${HOMEDIR}/data/kafka:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      # fix error of fluentd: error_class=Kafka::MessageSizeTooLarge error="Kafka::MessageSizeTooLarge"
      - KAFKA_CFG_MESSAGE_MAX_BYTES=536870912 # 512M
      # data retention settings
      - KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=10000 # 10s
      - KAFKA_CFG_LOG_RETENTION_HOURS=1 # 1hour
      - KAFKA_CFG_LOG_RETENTION_BYTES=1073741824  #1GB
    depends_on:
      - zookeeper

  logstash:
    image: logstash:7.5.1
    container_name: LOGSTASH
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 9600:9600
    volumes:
      - ${HOMEDIR}/conf.d/logstash/general.conf:/usr/share/logstash/pipeline/general/logstash.conf
      - ${HOMEDIR}/conf.d/logstash/patterns_dir:/usr/share/logstash/patterns_dir
      - ${HOMEDIR}/conf.d/logstash/index-template/general-template.tmpl:/usr/share/logstash/general-template.tmpl
      - ${HOMEDIR}/conf.d/logstash/index-lifecycle/general-ilm:/usr/share/logstash/index-lifecycle/general-ilm
      - ${HOMEDIR}/conf.d/logstash.pipelines:/usr/share/logstash/config/pipelines.yml
      - ${HOMEDIR}/scripts/cmds-in-logstash:/usr/share/logstash/cmds-in-logstash
    environment:
      - ES_INDEX
    entrypoint:
      - bash
      - -c
      - "/usr/share/logstash/cmds-in-logstash/create-index-lifecycle.sh && /usr/local/bin/docker-entrypoint -r"
    
    
  nginx:
    image: nginx:latest
    container_name: NGINX
    ports:
      - 20000:20000/udp
      - 80:80
    volumes:
      - ${HOMEDIR}/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ${HOMEDIR}/conf.d/nginx-dashboards:/etc/nginx/dashboards
      - ${HOMEDIR}/logs/nginx:/var/log/nginx
    depends_on:
      - fluentd
